site_name: IMPLANTACIÓN DE SISTEMAS OPERATIVOS
site_url: https://example.com/
nav:
  - Home: index.html
  - UD1 S.O. ESTRUCTURA Y VIRTUALIZACIÓN:
      - Estructura: ./UD1/Estructura.md
      - Bios: ./UD1/bios.md
      - Virtualización: ./UD1/virtual.md
      - LXD: ./UD1/lxd.md
      - Actividades: ./UD1/Actividades.md

  - UD2 CONFIGURACIÓN DE LOS SO:
      - Introducción Terminal: ./UD2/IntroTerminal.md
      - Estructura Directorios: ./UD2/EstructuraDirectorios.md
      - Gestión Archivos: ./UD2/gestionArchivos.md
      - Redirecciones: ./UD2/redirecciones.md
      - Filtros: ./UD2/filtros.md
      - Búsqueda Archivos: ./UD2/busquedaArchivos.md
      - Administración de memoria secundaria: ./UD2/AdminMemoriaSecundaria.md
      - Gestor de Arranque: ./UD2/gestorArranque.md
      - Permisos básicos: ./UD2/permisosBasicos.md
      - Actividades: ./UD2/Actividades.md

  - UD3.Administración de software base y aplicaciones:
      - Instalación en Windows: ./UD3/InstaWindow.md
      - Instalación en Linux: ./UD3/InstaLinux.md
      - Gestión de procesos: ./UD3/procesosLinux.md
      - Gestión de Servicios: ./UD3/GestiServicios.md
      - Programación de Tareas: ./UD3/programaTareas.md
      - Actualización del Sistema: ./UD3/actuSisOp.md
      - Registro de Windows: ./UD3/registroWindow.md
      - Actividades: ./UD3/Actividades.md

  - UD4.Instalación de servicios de Directorios:
      - Sistema de organización de redes: ./UD4/sistemaRedes.md
      - Configuración del protocolo TCP/IP: ./UD4/IP.md
      - Instalación del servicio de Directorio: ./UD4/instaServDirectorio.md
theme:
  name: material
  icon:
    admonition:
      example: octicons/terminal-16
  font:
    text: Roboto
    code: Roboto Mono
  features:
    # - navigation.sections
    - navigation.top
    - navigation.path
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - toc.integrate
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.keys
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - stylesheets/extra.css
